<a href="https://colab.research.google.com/github/mr-cri-spy/Python-libraries/blob/main/Numpy%2BPandas%2BEDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import numpy as np

In [ ]:
#creating arrays
a= np.array([10, 20, 30, 40,50])

In [ ]:
print(a.shape) #shape
print(a.ndim) #dimension

(5,)
1


In [ ]:
print(a[1]) #indexing
print(a[1:4]) #Slicing

20
[20 30 40]


In [ ]:
#Boolean masking
print(a[a>25])

[30 40 50]


In [ ]:
#math Operations
print(np.mean(a)) #mean
print(np.sum(a)) #sum
print(np.std(a)) #standard deviation

30.0
150
14.142135623730951


In [ ]:
#reshaping
b = a.reshape(5,1)
print(b)

[[10]
 [20]
 [30]
 [40]
 [50]]


In [ ]:
print(a*2) #Vectorized operations
#Vectorized operations are a way of performing computations on entire arrays (or vectors) of data at once, instead of using explicit loops to process one element at a time


[ 20  40  60  80 100]


In [ ]:
#missing value
c = np.array([1,2, np.nan, 4])
print(np.nanmean(c))
print(c)
c1 = np.nanmean(c)
print(c1)
c2 = np.append(c, c1)
print(c2)

2.3333333333333335
[ 1.  2. nan  4.]
2.3333333333333335
[1.         2.                nan 4.         2.33333333]


NumPy uses contiguous memory, C-based backend, and vectorized operations, which reduce Python-level loops and overhead, making it much faster

Vectorization means performing operations on entire arrays at once without using explicit loops, which improves speed and performance.

#Pandas + EDA

Pandas is a python library used for data manipulation and analysis it provides DataFrame and seies structures that allows us to clean filter group , merge, and analyze structured data efficiency

In [ ]:
import pandas as pd

#create DataFrame
data = {
    "name": ["a","b","c","d"],
    "age": [10,20,None,40],
    "salary": [3000, 4000,5000,None]
}

In [ ]:
df = pd.DataFrame(data)
print(df)

  name   age  salary
0    a  10.0  3000.0
1    b  20.0  4000.0
2    c   NaN  5000.0
3    d  40.0     NaN


In [ ]:
#checking the missing value
print(df.isnull())

    name    age  salary
0  False  False   False
1  False  False   False
2  False   True   False
3  False  False    True


In [ ]:
#Filling the missing value
df["age"].fillna(df["age"].mean(), inplace=True)
df["salary"].fillna(df["salary"].mean(), inplace=True)

print(df.isnull())



    name    age  salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False


/tmp/ipython-input-4052381695.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)
/tmp/ipython-input-4052381695.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try us

In [ ]:
#drop rows with missing values
#df.dropna()

#filtering
print(df[df["age"]>24])


  name   age  salary
3    d  40.0  4000.0


In [ ]:
#sorting
print(df.sort_values(by="salary"))

  name        age  salary
0    a  10.000000  3000.0
1    b  20.000000  4000.0
3    d  40.000000  4000.0
2    c  23.333333  5000.0


In [ ]:
#Grouping
print(df.groupby("age").mean(numeric_only=True))

           salary
age              
10.000000  3000.0
20.000000  4000.0
23.333333  5000.0
40.000000  4000.0


In [ ]:
#Exploratory Data Analysis(EDA)
#EDA is the process of exploring data to understand its structure, patterns, trends, and anomalies before applying any modeling or decision-making. It helps in identifying missing values, outliers, correlations, and overall data behavior.

import pandas as pd
data = {
    "product": ["A","B","C","D","E"],
    "sales":[200, 300 , None , 400 , 500],
    "Profit":[20,30,25,None,50]
}

df = pd.DataFrame(data)

In [ ]:
print(df)

  product  sales  Profit
0       A  200.0    20.0
1       B  300.0    30.0
2       C    NaN    25.0
3       D  400.0     NaN
4       E  500.0    50.0


In [ ]:
print(df.isnull())

   product  sales  Profit
0    False  False   False
1    False  False   False
2    False   True   False
3    False  False    True
4    False  False   False


In [ ]:
df["sales"].fillna(df["sales"].mean(),inplace=True)
df["Profit"].fillna(df["Profit"].mean(), inplace = True)
print(df)

  product  sales  Profit
0       A  200.0   20.00
1       B  300.0   30.00
2       C  350.0   25.00
3       D  400.0   31.25
4       E  500.0   50.00


/tmp/ipython-input-1191508393.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["sales"].fillna(df["sales"].mean(),inplace=True)
/tmp/ipython-input-1191508393.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try

In [ ]:
print(df[df["sales"]>300])

  product  sales  Profit
2       C  350.0   25.00
3       D  400.0   31.25
4       E  500.0   50.00
